<?php

	if (!defined('ABSPATH')) {
		exit;
	}

	const ACFAI_ALL_LANGUAGES = [
		'aa' => ['name' => 'Afar', 'flag' => ''],
		'ab' => ['name' => 'Abkhaz', 'flag' => ''],
		'ae' => ['name' => 'Avestan', 'flag' => ''],
		'af' => ['name' => 'Afrikaans', 'flag' => ''],
		'ak' => ['name' => 'Akan', 'flag' => ''],
		'am' => ['name' => 'Amharic', 'flag' => ''],
		'an' => ['name' => 'Aragonese', 'flag' => ''],
		'ar' => ['name' => 'Arabic', 'flag' => 'assets/images/flags/sa.svg'],
		'as' => ['name' => 'Assamese', 'flag' => ''],
		'av' => ['name' => 'Avaric', 'flag' => ''],
		'ay' => ['name' => 'Aymara', 'flag' => ''],
		'az' => ['name' => 'Azerbaijani', 'flag' => 'assets/images/flags/az.svg'],
		'ba' => ['name' => 'Bashkir', 'flag' => ''],
		'be' => ['name' => 'Belarusian', 'flag' => 'assets/images/flags/by.svg'],
		'bg' => ['name' => 'Bulgarian', 'flag' => 'assets/images/flags/bg.svg'],
		'bh' => ['name' => 'Bihari', 'flag' => ''],
		'bi' => ['name' => 'Bislama', 'flag' => ''],
		'bm' => ['name' => 'Bambara', 'flag' => ''],
		'bn' => ['name' => 'Bengali', 'flag' => 'assets/images/flags/bd.svg'],
		'bo' => ['name' => 'Tibetan', 'flag' => ''],
		'br' => ['name' => 'Breton', 'flag' => ''],
		'bs' => ['name' => 'Bosnian', 'flag' => 'assets/images/flags/ba.svg'],
		'ca' => ['name' => 'Catalan', 'flag' => 'assets/images/flags/es-ct.svg'],
		'ce' => ['name' => 'Chechen', 'flag' => ''],
		'ch' => ['name' => 'Chamorro', 'flag' => ''],
		'co' => ['name' => 'Corsican', 'flag' => ''],
		'cr' => ['name' => 'Cree', 'flag' => ''],
		'cs' => ['name' => 'Czech', 'flag' => 'assets/images/flags/cz.svg'],
		'cu' => ['name' => 'Church Slavic', 'flag' => ''],
		'cv' => ['name' => 'Chuvash', 'flag' => ''],
		'cy' => ['name' => 'Welsh', 'flag' => 'assets/images/flags/gb-wls.svg'],
		'da' => ['name' => 'Danish', 'flag' => 'assets/images/flags/dk.svg'],
		'de' => ['name' => 'German', 'flag' => 'assets/images/flags/de.svg'],
		'dv' => ['name' => 'Divehi', 'flag' => 'assets/images/flags/mv.svg'],
		'dz' => ['name' => 'Dzongkha', 'flag' => 'assets/images/flags/bt.svg'],
		'ee' => ['name' => 'Ewe', 'flag' => ''],
		'el' => ['name' => 'Greek', 'flag' => 'assets/images/flags/gr.svg'],
		'en' => ['name' => 'English', 'flag' => 'assets/images/flags/gb.svg'],
		'eo' => ['name' => 'Esperanto', 'flag' => ''],
		'es' => ['name' => 'Spanish', 'flag' => 'assets/images/flags/es.svg'],
		'et' => ['name' => 'Estonian', 'flag' => 'assets/images/flags/ee.svg'],
		'eu' => ['name' => 'Basque', 'flag' => ''],
		'fa' => ['name' => 'Persian', 'flag' => 'assets/images/flags/ir.svg'],
		'ff' => ['name' => 'Fulah', 'flag' => ''],
		'fi' => ['name' => 'Finnish', 'flag' => 'assets/images/flags/fi.svg'],
		'fj' => ['name' => 'Fijian', 'flag' => 'assets/images/flags/fj.svg'],
		'fo' => ['name' => 'Faroese', 'flag' => 'assets/images/flags/fo.svg'],
		'fr' => ['name' => 'French', 'flag' => 'assets/images/flags/fr.svg'],
		'fy' => ['name' => 'Western Frisian', 'flag' => ''],
		'ga' => ['name' => 'Irish', 'flag' => 'assets/images/flags/ie.svg'],
		'gd' => ['name' => 'Scottish Gaelic', 'flag' => 'assets/images/flags/gb-sct.svg'],
		'gl' => ['name' => 'Galician', 'flag' => 'assets/images/flags/es-ga.svg'],
		'gn' => ['name' => 'Guarani', 'flag' => 'assets/images/flags/py.svg'],
		'gu' => ['name' => 'Gujarati', 'flag' => 'assets/images/flags/in.svg'],
		'gv' => ['name' => 'Manx', 'flag' => 'assets/images/flags/im.svg'],
		'ha' => ['name' => 'Hausa', 'flag' => 'assets/images/flags/ng.svg'],
		'he' => ['name' => 'Hebrew', 'flag' => 'assets/images/flags/il.svg'],
		'hi' => ['name' => 'Hindi', 'flag' => 'assets/images/flags/in.svg'],
		'ho' => ['name' => 'Hiri Motu', 'flag' => 'assets/images/flags/pg.svg'],
		'hr' => ['name' => 'Croatian', 'flag' => 'assets/images/flags/hr.svg'],
		'ht' => ['name' => 'Haitian', 'flag' => 'assets/images/flags/ht.svg'],
		'hu' => ['name' => 'Hungarian', 'flag' => 'assets/images/flags/hu.svg'],
		'hy' => ['name' => 'Armenian', 'flag' => 'assets/images/flags/am.svg'],
		'hz' => ['name' => 'Herero', 'flag' => ''],
		'ia' => ['name' => 'Interlingua', 'flag' => ''],
		'id' => ['name' => 'Indonesian', 'flag' => 'assets/images/flags/id.svg'],
		'ie' => ['name' => 'Interlingue', 'flag' => ''],
		'ig' => ['name' => 'Igbo', 'flag' => 'assets/images/flags/ng.svg'],
		'ii' => ['name' => 'Sichuan Yi', 'flag' => ''],
		'ik' => ['name' => 'Inupiaq', 'flag' => ''],
		'io' => ['name' => 'Ido', 'flag' => ''],
		'is' => ['name' => 'Icelandic', 'flag' => 'assets/images/flags/is.svg'],
		'it' => ['name' => 'Italian', 'flag' => 'assets/images/flags/it.svg'],
		'iu' => ['name' => 'Inuktitut', 'flag' => 'assets/images/flags/ca.svg'],
		'ja' => ['name' => 'Japanese', 'flag' => 'assets/images/flags/jp.svg'],
		'jv' => ['name' => 'Javanese', 'flag' => 'assets/images/flags/id.svg'],
		'ka' => ['name' => 'Georgian', 'flag' => 'assets/images/flags/ge.svg'],
		'kg' => ['name' => 'Kongo', 'flag' => ''],
		'ki' => ['name' => 'Kikuyu', 'flag' => 'assets/images/flags/ke.svg'],
		'kj' => ['name' => 'Kuanyama', 'flag' => 'assets/images/flags/ao.svg'],
		'kk' => ['name' => 'Kazakh', 'flag' => 'assets/images/flags/kz.svg'],
		'kl' => ['name' => 'Kalaallisut', 'flag' => 'assets/images/flags/gl.svg'],
		'km' => ['name' => 'Khmer', 'flag' => 'assets/images/flags/kh.svg'],
		'kn' => ['name' => 'Kannada', 'flag' => 'assets/images/flags/in.svg'],
		'ko' => ['name' => 'Korean', 'flag' => 'assets/images/flags/kr.svg'],
		'kr' => ['name' => 'Kanuri', 'flag' => ''],
		'ks' => ['name' => 'Kashmiri', 'flag' => 'assets/images/flags/in.svg'],
		'ku' => ['name' => 'Kurdish', 'flag' => 'assets/images/flags/iq.svg'],
		'kv' => ['name' => 'Komi', 'flag' => 'assets/images/flags/ru.svg'],
		'kw' => ['name' => 'Cornish', 'flag' => 'assets/images/flags/gb-eng.svg'],
		'ky' => ['name' => 'Kirghiz', 'flag' => 'assets/images/flags/kg.svg'],
		'la' => ['name' => 'Latin', 'flag' => 'assets/images/flags/va.svg'],
		'lb' => ['name' => 'Luxembourgish', 'flag' => 'assets/images/flags/lu.svg'],
		'lg' => ['name' => 'Ganda', 'flag' => 'assets/images/flags/ug.svg'],
		'li' => ['name' => 'Limburgish', 'flag' => ''],
		'ln' => ['name' => 'Lingala', 'flag' => 'assets/images/flags/cd.svg'],
		'lo' => ['name' => 'Lao', 'flag' => 'assets/images/flags/la.svg'],
		'lt' => ['name' => 'Lithuanian', 'flag' => 'assets/images/flags/lt.svg'],
		'lu' => ['name' => 'Luba-Katanga', 'flag' => 'assets/images/flags/cd.svg'],
		'lv' => ['name' => 'Latvian', 'flag' => 'assets/images/flags/lv.svg'],
		'mg' => ['name' => 'Malagasy', 'flag' => 'assets/images/flags/mg.svg'],
		'mh' => ['name' => 'Marshallese', 'flag' => 'assets/images/flags/mh.svg'],
		'mi' => ['name' => 'Maori', 'flag' => 'assets/images/flags/nz.svg'],
		'mk' => ['name' => 'Macedonian', 'flag' => 'assets/images/flags/mk.svg'],
		'ml' => ['name' => 'Malayalam', 'flag' => 'assets/images/flags/in.svg'],
		'mn' => ['name' => 'Mongolian', 'flag' => 'assets/images/flags/mn.svg'],
		'mr' => ['name' => 'Marathi', 'flag' => 'assets/images/flags/in.svg'],
		'ms' => ['name' => 'Malay', 'flag' => 'assets/images/flags/my.svg'],
		'mt' => ['name' => 'Maltese', 'flag' => 'assets/images/flags/mt.svg'],
		'my' => ['name' => 'Burmese', 'flag' => 'assets/images/flags/mm.svg'],
		'na' => ['name' => 'Nauru', 'flag' => 'assets/images/flags/nr.svg'],
		'nb' => ['name' => 'Norwegian Bokmål', 'flag' => 'assets/images/flags/no.svg'],
		'nd' => ['name' => 'North Ndebele', 'flag' => 'assets/images/flags/zw.svg'],
		'ne' => ['name' => 'Nepali', 'flag' => 'assets/images/flags/np.svg'],
		'ng' => ['name' => 'Ndonga', 'flag' => 'assets/images/flags/na.svg'],
		'nl' => ['name' => 'Dutch', 'flag' => 'assets/images/flags/nl.svg'],
		'nn' => ['name' => 'Norwegian Nynorsk', 'flag' => 'assets/images/flags/no.svg'],
		'no' => ['name' => 'Norwegian', 'flag' => 'assets/images/flags/no.svg'],
		'nr' => ['name' => 'South Ndebele', 'flag' => 'assets/images/flags/za.svg'],
		'nv' => ['name' => 'Navajo', 'flag' => 'assets/images/flags/us.svg'],
		'ny' => ['name' => 'Chichewa', 'flag' => 'assets/images/flags/mw.svg'],
		'oc' => ['name' => 'Occitan', 'flag' => 'assets/images/flags/fr.svg'],
		'oj' => ['name' => 'Ojibwa', 'flag' => 'assets/images/flags/ca.svg'],
		'om' => ['name' => 'Oromo', 'flag' => 'assets/images/flags/et.svg'],
		'or' => ['name' => 'Oriya', 'flag' => 'assets/images/flags/in.svg'],
		'os' => ['name' => 'Ossetian', 'flag' => 'assets/images/flags/ru.svg'],
		'pa' => ['name' => 'Punjabi', 'flag' => 'assets/images/flags/in.svg'],
		'pi' => ['name' => 'Pali', 'flag' => ''],
		'pl' => ['name' => 'Polish', 'flag' => 'assets/images/flags/pl.svg'],
		'ps' => ['name' => 'Pashto', 'flag' => 'assets/images/flags/af.svg'],
		'pt' => ['name' => 'Portuguese', 'flag' => 'assets/images/flags/pt.svg'],
		'qu' => ['name' => 'Quechua', 'flag' => 'assets/images/flags/bo.svg'],
		'rm' => ['name' => 'Romansh', 'flag' => 'assets/images/flags/ch.svg'],
		'rn' => ['name' => 'Kirundi', 'flag' => 'assets/images/flags/bi.svg'],
		'ro' => ['name' => 'Romanian', 'flag' => 'assets/images/flags/ro.svg'],
		'ru' => ['name' => 'Russian', 'flag' => 'assets/images/flags/ru.svg'],
		'rw' => ['name' => 'Kinyarwanda', 'flag' => 'assets/images/flags/rw.svg'],
		'sa' => ['name' => 'Sanskrit', 'flag' => 'assets/images/flags/in.svg'],
		'sc' => ['name' => 'Sardinian', 'flag' => 'assets/images/flags/it.svg'],
		'sd' => ['name' => 'Sindhi', 'flag' => 'assets/images/flags/pk.svg'],
		'se' => ['name' => 'Northern Sami', 'flag' => 'assets/images/flags/no.svg'],
		'sg' => ['name' => 'Sango', 'flag' => 'assets/images/flags/cf.svg'],
		'si' => ['name' => 'Sinhala', 'flag' => 'assets/images/flags/lk.svg'],
		'sk' => ['name' => 'Slovak', 'flag' => 'assets/images/flags/sk.svg'],
		'sl' => ['name' => 'Slovenian', 'flag' => 'assets/images/flags/si.svg'],
		'sm' => ['name' => 'Samoan', 'flag' => 'assets/images/flags/ws.svg'],
		'sn' => ['name' => 'Shona', 'flag' => 'assets/images/flags/zw.svg'],
		'so' => ['name' => 'Somali', 'flag' => 'assets/images/flags/so.svg'],
		'sq' => ['name' => 'Albanian', 'flag' => 'assets/images/flags/al.svg'],
		'sr' => ['name' => 'Serbian', 'flag' => 'assets/images/flags/rs.svg'],
		'ss' => ['name' => 'Swati', 'flag' => 'assets/images/flags/sz.svg'],
		'st' => ['name' => 'Southern Sotho', 'flag' => 'assets/images/flags/ls.svg'],
		'su' => ['name' => 'Sundanese', 'flag' => 'assets/images/flags/id.svg'],
		'sv' => ['name' => 'Swedish', 'flag' => 'assets/images/flags/se.svg'],
		'sw' => ['name' => 'Swahili', 'flag' => 'assets/images/flags/tz.svg'],
		'ta' => ['name' => 'Tamil', 'flag' => 'assets/images/flags/in.svg'],
		'te' => ['name' => 'Telugu', 'flag' => 'assets/images/flags/in.svg'],
		'tg' => ['name' => 'Tajik', 'flag' => 'assets/images/flags/tj.svg'],
		'th' => ['name' => 'Thai', 'flag' => 'assets/images/flags/th.svg'],
		'ti' => ['name' => 'Tigrinya', 'flag' => 'assets/images/flags/er.svg'],
		'tk' => ['name' => 'Turkmen', 'flag' => 'assets/images/flags/tm.svg'],
		'tl' => ['name' => 'Tagalog', 'flag' => 'assets/images/flags/ph.svg'],
		'tn' => ['name' => 'Tswana', 'flag' => 'assets/images/flags/bw.svg'],
		'to' => ['name' => 'Tonga', 'flag' => 'assets/images/flags/to.svg'],
		'tr' => ['name' => 'Turkish', 'flag' => 'assets/images/flags/tr.svg'],
		'ts' => ['name' => 'Tsonga', 'flag' => 'assets/images/flags/za.svg'],
		'tt' => ['name' => 'Tatar', 'flag' => 'assets/images/flags/ru.svg'],
		'tw' => ['name' => 'Twi', 'flag' => 'assets/images/flags/gh.svg'],
		'ty' => ['name' => 'Tahitian', 'flag' => 'assets/images/flags/pf.svg'],
		'ug' => ['name' => 'Uyghur', 'flag' => 'assets/images/flags/cn.svg'],
		'uk' => ['name' => 'Ukrainian', 'flag' => 'assets/images/flags/ua.svg'],
		'ur' => ['name' => 'Urdu', 'flag' => 'assets/images/flags/pk.svg'],
		'uz' => ['name' => 'Uzbek', 'flag' => 'assets/images/flags/uz.svg'],
		've' => ['name' => 'Venda', 'flag' => 'assets/images/flags/za.svg'],
		'vi' => ['name' => 'Vietnamese', 'flag' => 'assets/images/flags/vn.svg'],
		'vo' => ['name' => 'Volapük', 'flag' => ''],
		'wa' => ['name' => 'Walloon', 'flag' => 'assets/images/flags/be.svg'],
		'wo' => ['name' => 'Wolof', 'flag' => 'assets/images/flags/sn.svg'],
		'xh' => ['name' => 'Xhosa', 'flag' => 'assets/images/flags/za.svg'],
		'yi' => ['name' => 'Yiddish', 'flag' => 'assets/images/flags/il.svg'],
		'yo' => ['name' => 'Yoruba', 'flag' => 'assets/images/flags/ng.svg'],
		'za' => ['name' => 'Zhuang', 'flag' => 'assets/images/flags/cn.svg'],
		'zh' => ['name' => 'Chinese', 'flag' => 'assets/images/flags/cn.svg'],
		'zu' => ['name' => 'Zulu', 'flag' => 'assets/images/flags/za.svg'],
	];